[project]
name = "chat-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.8",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
